# Justification: Printing to system out is valid use case for the console reporter as one of the outcomes of this app
com.lyr.report.ConsoleReporter=SystemPrintln
# Justification: This is a console app not a web app where exit values needs to be handled
com.lyr.cli.Lyr=DoNotTerminateVM