package com.lyr.rule.lambda;

public enum LambdaReason {
    FUNCTION_CONCURRENCY_MISMATCH,
    FUNCTION_NOT_FOUND,
    NO_EVENT_SOURCE_MAPPINGS,
    ALL_EVENT_MAPPINGS_ARE_NOT_ENABLED,
    ALL_EVENT_MAPPINGS_ARE_ENABLED,
    ALL_EVENT_MAPPINGS_ARE_DISABLED,
    ALL_EVENT_MAPPINGS_ARE_NOT_DISABLED
}
